<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="webspecchangemodel"
    nsURI="ar.edu.unlp.info.lifia.webspecchange" nsPrefix="ar.edu.unlp.info.lifia.webspecchange">
  <eClassifiers xsi:type="ecore:EClass" name="WebSpecChangeObject">
    <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#//WebSpecChange"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebSpecChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewInteraction" eSuperTypes="#//WebSpecChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewNavigation" eSuperTypes="#//WebSpecChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceInteraction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetInteraction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewWidget" eSuperTypes="#//WebSpecChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetContainer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyChange" eSuperTypes="#//WebSpecChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeletedInteraction" eSuperTypes="#//WebSpecChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
