/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

import org.webspeclanguage.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class ALowerCompExpr extends PCompExpr
{
    private PCompExpr _left_;
    private TLower _lower_;
    private PNumExpr _right_;

    public ALowerCompExpr()
    {
        // Constructor
    }

    public ALowerCompExpr(
        @SuppressWarnings("hiding") PCompExpr _left_,
        @SuppressWarnings("hiding") TLower _lower_,
        @SuppressWarnings("hiding") PNumExpr _right_)
    {
        // Constructor
        setLeft(_left_);

        setLower(_lower_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ALowerCompExpr(
            cloneNode(this._left_),
            cloneNode(this._lower_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALowerCompExpr(this);
    }

    public PCompExpr getLeft()
    {
        return this._left_;
    }

    public void setLeft(PCompExpr node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TLower getLower()
    {
        return this._lower_;
    }

    public void setLower(TLower node)
    {
        if(this._lower_ != null)
        {
            this._lower_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lower_ = node;
    }

    public PNumExpr getRight()
    {
        return this._right_;
    }

    public void setRight(PNumExpr node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._lower_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._lower_ == child)
        {
            this._lower_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PCompExpr) newChild);
            return;
        }

        if(this._lower_ == oldChild)
        {
            setLower((TLower) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PNumExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
