/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

import org.webspeclanguage.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANotExpr extends PExpr
{
    private TNot _not_;
    private PCompExpr _compExpr_;

    public ANotExpr()
    {
        // Constructor
    }

    public ANotExpr(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PCompExpr _compExpr_)
    {
        // Constructor
        setNot(_not_);

        setCompExpr(_compExpr_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpr(
            cloneNode(this._not_),
            cloneNode(this._compExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpr(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PCompExpr getCompExpr()
    {
        return this._compExpr_;
    }

    public void setCompExpr(PCompExpr node)
    {
        if(this._compExpr_ != null)
        {
            this._compExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._compExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._compExpr_ == child)
        {
            this._compExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._compExpr_ == oldChild)
        {
            setCompExpr((PCompExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
