/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

import org.webspeclanguage.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class AWidgetReferenceValue extends PValue
{
    private TIdentifier _interaction_;
    private TPoint _point_;
    private TIdentifier _widget_;

    public AWidgetReferenceValue()
    {
        // Constructor
    }

    public AWidgetReferenceValue(
        @SuppressWarnings("hiding") TIdentifier _interaction_,
        @SuppressWarnings("hiding") TPoint _point_,
        @SuppressWarnings("hiding") TIdentifier _widget_)
    {
        // Constructor
        setInteraction(_interaction_);

        setPoint(_point_);

        setWidget(_widget_);

    }

    @Override
    public Object clone()
    {
        return new AWidgetReferenceValue(
            cloneNode(this._interaction_),
            cloneNode(this._point_),
            cloneNode(this._widget_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWidgetReferenceValue(this);
    }

    public TIdentifier getInteraction()
    {
        return this._interaction_;
    }

    public void setInteraction(TIdentifier node)
    {
        if(this._interaction_ != null)
        {
            this._interaction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._interaction_ = node;
    }

    public TPoint getPoint()
    {
        return this._point_;
    }

    public void setPoint(TPoint node)
    {
        if(this._point_ != null)
        {
            this._point_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._point_ = node;
    }

    public TIdentifier getWidget()
    {
        return this._widget_;
    }

    public void setWidget(TIdentifier node)
    {
        if(this._widget_ != null)
        {
            this._widget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._widget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._interaction_)
            + toString(this._point_)
            + toString(this._widget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._interaction_ == child)
        {
            this._interaction_ = null;
            return;
        }

        if(this._point_ == child)
        {
            this._point_ = null;
            return;
        }

        if(this._widget_ == child)
        {
            this._widget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._interaction_ == oldChild)
        {
            setInteraction((TIdentifier) newChild);
            return;
        }

        if(this._point_ == oldChild)
        {
            setPoint((TPoint) newChild);
            return;
        }

        if(this._widget_ == oldChild)
        {
            setWidget((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
