/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

public abstract class PVariableorliteralarray extends Node
{
    // Empty body
}
