/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

import org.webspeclanguage.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class TNumberType extends Token
{
    public TNumberType()
    {
        super.setText("Number");
    }

    public TNumberType(int line, int pos)
    {
        super.setText("Number");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumberType(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumberType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNumberType text.");
    }
}
