      <form class="well form-horizontal">
        <fieldset>
        <div class="control-group">
          <label class="control-label">Name:</label>&nbsp;&nbsp;
          <input id="name" type="text" value="{name}">
          <input type="hidden" id="projectId" name="projectId" value="{id}">
        </div>
        <div class="form-actions">
        <button id="saveButton" class="btn btn-primary">Save</button>
        </div>
        </fieldset>
      </form>