/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.impl.expression.parser.node;

import org.webspeclanguage.impl.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class AMulFactor extends PFactor
{
    private PFactor _left_;
    private TMul _mul_;
    private PValue _right_;

    public AMulFactor()
    {
        // Constructor
    }

    public AMulFactor(
        @SuppressWarnings("hiding") PFactor _left_,
        @SuppressWarnings("hiding") TMul _mul_,
        @SuppressWarnings("hiding") PValue _right_)
    {
        // Constructor
        setLeft(_left_);

        setMul(_mul_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AMulFactor(
            cloneNode(this._left_),
            cloneNode(this._mul_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMulFactor(this);
    }

    public PFactor getLeft()
    {
        return this._left_;
    }

    public void setLeft(PFactor node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TMul getMul()
    {
        return this._mul_;
    }

    public void setMul(TMul node)
    {
        if(this._mul_ != null)
        {
            this._mul_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mul_ = node;
    }

    public PValue getRight()
    {
        return this._right_;
    }

    public void setRight(PValue node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._mul_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._mul_ == child)
        {
            this._mul_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PFactor) newChild);
            return;
        }

        if(this._mul_ == oldChild)
        {
            setMul((TMul) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
