<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleTest" eSuperTypes="#//Test">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//TestItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite" eSuperTypes="#//Test">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//Test" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestItem">
    <eOperations name="execute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//TestItem">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//TestItem">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
</ecore:EPackage>
