/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.impl.expression.parser.node;

import org.webspeclanguage.impl.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class AManyactionsActions extends PActions
{
    private PAction _action_;
    private TSemicolon _semicolon_;
    private PActions _actions_;

    public AManyactionsActions()
    {
        // Constructor
    }

    public AManyactionsActions(
        @SuppressWarnings("hiding") PAction _action_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") PActions _actions_)
    {
        // Constructor
        setAction(_action_);

        setSemicolon(_semicolon_);

        setActions(_actions_);

    }

    @Override
    public Object clone()
    {
        return new AManyactionsActions(
            cloneNode(this._action_),
            cloneNode(this._semicolon_),
            cloneNode(this._actions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyactionsActions(this);
    }

    public PAction getAction()
    {
        return this._action_;
    }

    public void setAction(PAction node)
    {
        if(this._action_ != null)
        {
            this._action_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._action_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public PActions getActions()
    {
        return this._actions_;
    }

    public void setActions(PActions node)
    {
        if(this._actions_ != null)
        {
            this._actions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actions_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._action_)
            + toString(this._semicolon_)
            + toString(this._actions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._action_ == child)
        {
            this._action_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._actions_ == child)
        {
            this._actions_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._action_ == oldChild)
        {
            setAction((PAction) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._actions_ == oldChild)
        {
            setActions((PActions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
