/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

import org.webspeclanguage.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class AStringTypeType extends PType
{
    private TStringType _stringType_;

    public AStringTypeType()
    {
        // Constructor
    }

    public AStringTypeType(
        @SuppressWarnings("hiding") TStringType _stringType_)
    {
        // Constructor
        setStringType(_stringType_);

    }

    @Override
    public Object clone()
    {
        return new AStringTypeType(
            cloneNode(this._stringType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringTypeType(this);
    }

    public TStringType getStringType()
    {
        return this._stringType_;
    }

    public void setStringType(TStringType node)
    {
        if(this._stringType_ != null)
        {
            this._stringType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringType_ == child)
        {
            this._stringType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringType_ == oldChild)
        {
            setStringType((TStringType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
