/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.webspeclanguage.expression.parser.node;

import org.webspeclanguage.expression.parser.analysis.*;

@SuppressWarnings("nls")
public final class AWidgetPropertyReferenceValue extends PValue
{
    private TIdentifier _interaction_;
    private TPoint _p1_;
    private TIdentifier _widget_;
    private TPoint _p2_;
    private TIdentifier _property_;

    public AWidgetPropertyReferenceValue()
    {
        // Constructor
    }

    public AWidgetPropertyReferenceValue(
        @SuppressWarnings("hiding") TIdentifier _interaction_,
        @SuppressWarnings("hiding") TPoint _p1_,
        @SuppressWarnings("hiding") TIdentifier _widget_,
        @SuppressWarnings("hiding") TPoint _p2_,
        @SuppressWarnings("hiding") TIdentifier _property_)
    {
        // Constructor
        setInteraction(_interaction_);

        setP1(_p1_);

        setWidget(_widget_);

        setP2(_p2_);

        setProperty(_property_);

    }

    @Override
    public Object clone()
    {
        return new AWidgetPropertyReferenceValue(
            cloneNode(this._interaction_),
            cloneNode(this._p1_),
            cloneNode(this._widget_),
            cloneNode(this._p2_),
            cloneNode(this._property_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWidgetPropertyReferenceValue(this);
    }

    public TIdentifier getInteraction()
    {
        return this._interaction_;
    }

    public void setInteraction(TIdentifier node)
    {
        if(this._interaction_ != null)
        {
            this._interaction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._interaction_ = node;
    }

    public TPoint getP1()
    {
        return this._p1_;
    }

    public void setP1(TPoint node)
    {
        if(this._p1_ != null)
        {
            this._p1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p1_ = node;
    }

    public TIdentifier getWidget()
    {
        return this._widget_;
    }

    public void setWidget(TIdentifier node)
    {
        if(this._widget_ != null)
        {
            this._widget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._widget_ = node;
    }

    public TPoint getP2()
    {
        return this._p2_;
    }

    public void setP2(TPoint node)
    {
        if(this._p2_ != null)
        {
            this._p2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p2_ = node;
    }

    public TIdentifier getProperty()
    {
        return this._property_;
    }

    public void setProperty(TIdentifier node)
    {
        if(this._property_ != null)
        {
            this._property_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._property_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._interaction_)
            + toString(this._p1_)
            + toString(this._widget_)
            + toString(this._p2_)
            + toString(this._property_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._interaction_ == child)
        {
            this._interaction_ = null;
            return;
        }

        if(this._p1_ == child)
        {
            this._p1_ = null;
            return;
        }

        if(this._widget_ == child)
        {
            this._widget_ = null;
            return;
        }

        if(this._p2_ == child)
        {
            this._p2_ = null;
            return;
        }

        if(this._property_ == child)
        {
            this._property_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._interaction_ == oldChild)
        {
            setInteraction((TIdentifier) newChild);
            return;
        }

        if(this._p1_ == oldChild)
        {
            setP1((TPoint) newChild);
            return;
        }

        if(this._widget_ == oldChild)
        {
            setWidget((TIdentifier) newChild);
            return;
        }

        if(this._p2_ == oldChild)
        {
            setP2((TPoint) newChild);
            return;
        }

        if(this._property_ == oldChild)
        {
            setProperty((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
